name: Picasso - PR merge CI

on:
  pull_request:
    branches: [master]

jobs:
  specs:
    if: contains(github.event.pull_request.labels.*.name , 'WIP') != true
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # container:
    #   image: cypress/included:5.3.0
    #   options: --privileged # thanks to this we can increase number of file watchers below

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Increase max_user_watches
        run: echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies (from network)
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional

      - name: Install Dependencies (from cache)
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: |
          yarn policies set-version
          yarn install --frozen-lockfile --ignore-optional --offline

      - name: Lint
        run: yarn lint
