version: 2
registries:
  docker-registry-gcr-io:
    type: docker-registry
    url: https://gcr.io
    username: _json_key
    password: "${{secrets.DOCKER_REGISTRY_GCR_IO_PASSWORD}}"
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
  - no-jira
  versioning-strategy: increase
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
  - no-jira
  ignore:
  - dependency-name: node
    versions:
    - 16.pre.alpine
  registries:
  - docker-registry-gcr-io
