version: 2
registries:
  docker-registry-gcr-io:
    type: docker-registry
    url: https://gcr.io
    username: _json_key
    password: "${{secrets.DOCKER_REGISTRY_GCR_IO_PASSWORD}}"
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
  - no-jira
  versioning-strategy: increase
  ignore:
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.3
  - dependency-name: "@toptal/davinci"
    versions:
    - 1.0.65
  - dependency-name: d3-array
    versions:
    - 2.11.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: ssri
    versions:
    - 5.3.0
  registries:
  - npm-registry-registry-npmjs-org
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
  - no-jira
  ignore:
  - dependency-name: node
    versions:
    - 16.pre.alpine
  registries:
  - docker-registry-gcr-io
