version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  labels:
    - no-jira
  versioning-strategy: increase
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 2
  pull-request-branch-name:
    separator: "-"
  labels:
    - no-jira
    - dependencies
    - github-actions
