module.exports = [
  {
    group_name: 'Accordion',
    group_dependencies: [
      'packages/picasso/src/ButtonAction/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/AccordionSummary/',
      'packages/picasso/src/AccordionDetails/',
      'packages/picasso/src/Accordion/',
    ],
    components: [
      'packages/picasso/src/AccordionCompound/',
      'packages/picasso/src/Accordion/',
      'packages/picasso/src/AccordionDetails/',
      'packages/picasso/src/AccordionSummary/',
    ],
    instability: 2,
    responsibility: 1,
    accumulative_instability: 16,
    accumulative_responsibility: 3,
  },
  {
    group_name: 'ShowMore',
    group_dependencies: [
      'packages/picasso/src/ButtonAction/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/ShowMore/'],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 10,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Icons',
    group_dependencies: ['packages/picasso/src/utils/'],
    components: ['packages/picasso/src/Icon/'],
    instability: 1,
    responsibility: 33,
    accumulative_instability: 2,
    accumulative_responsibility: 117,
  },
  {
    group_name: 'AccountSelect',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/UserBadge/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Link/',
      'packages/picasso/src/MenuCompound/',
      'packages/picasso/src/Container/',
    ],
    components: ['packages/picasso/src/AccountSelect/'],
    instability: 6,
    responsibility: 0,
    accumulative_instability: 20,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Link',
    group_dependencies: [],
    components: ['packages/picasso/src/Link/'],
    instability: 0,
    responsibility: 2,
    accumulative_instability: 0,
    accumulative_responsibility: 9,
  },
  {
    group_name: 'Container',
    group_dependencies: ['packages/picasso/src/utils/'],
    components: ['packages/picasso/src/Container/'],
    instability: 1,
    responsibility: 39,
    accumulative_instability: 2,
    accumulative_responsibility: 120,
  },
  {
    group_name: 'Typography',
    group_dependencies: ['packages/picasso/src/utils/'],
    components: ['packages/picasso/src/Typography/'],
    instability: 1,
    responsibility: 38,
    accumulative_instability: 2,
    accumulative_responsibility: 101,
  },
  {
    group_name: 'Amount',
    group_dependencies: ['packages/picasso/src/Typography/'],
    components: ['packages/picasso/src/Amount/'],
    instability: 1,
    responsibility: 0,
    accumulative_instability: 2,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'UserBadge',
    group_dependencies: [
      'packages/picasso/src/Avatar/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/UserBadge/'],
    instability: 3,
    responsibility: 3,
    accumulative_instability: 10,
    accumulative_responsibility: 9,
  },
  {
    group_name: 'Button',
    group_dependencies: [
      'packages/picasso/src/ButtonGroup/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Radio/',
      'packages/picasso/src/ButtonCheckbox/',
      'packages/picasso/src/ButtonAction/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/ButtonSplit/',
      'packages/picasso/src/Checkbox/',
      'packages/picasso/src/Dropdown/',
      'packages/picasso/src/Loader/',
      'packages/picasso/src/ButtonGroupItem/',
      'packages/picasso/src/ButtonControlLabel/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/ButtonRadio/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/ButtonCompound/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/ButtonGroup/',
      'packages/picasso/src/ButtonGroupItem/',
      'packages/picasso/src/ButtonSplit/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/ButtonAction/',
      'packages/picasso/src/ButtonCheckbox/',
      'packages/picasso/src/ButtonControlLabel/',
      'packages/picasso/src/ButtonRadio/',
    ],
    instability: 7,
    responsibility: 23,
    accumulative_instability: 86,
    accumulative_responsibility: 50,
  },
  {
    group_name: 'Utils',
    group_dependencies: ['packages/picasso/src/Notification/'],
    components: ['packages/picasso/src/utils/'],
    instability: 1,
    responsibility: 42,
    accumulative_instability: 5,
    accumulative_responsibility: 262,
  },
  {
    group_name: 'Alert',
    group_dependencies: [
      'packages/picasso/src/Alert/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/ButtonSplit/',
      'packages/picasso/src/AlertInline/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/AlertCompound/',
      'packages/picasso/src/AlertInline/',
      'packages/picasso/src/Alert/',
    ],
    instability: 7,
    responsibility: 0,
    accumulative_instability: 46,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'ApplicationUpdateNotification',
    group_dependencies: [
      'packages/picasso/src/ApplicationUpdateNotification/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/ApplicationUpdateNotificationActions/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/ApplicationUpdateNotification/',
      'packages/picasso/src/ApplicationUpdateNotificationActions/',
      'packages/picasso/src/ApplicationUpdateNotificationCompound/',
    ],
    instability: 4,
    responsibility: 0,
    accumulative_instability: 22,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Autocomplete',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/Popper/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Input/',
      'packages/picasso/src/Loader/',
      'packages/picasso/src/MenuCompound/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/SelectOptions/',
    ],
    components: ['packages/picasso/src/Autocomplete/'],
    instability: 11,
    responsibility: 2,
    accumulative_instability: 55,
    accumulative_responsibility: 3,
  },
  {
    group_name: 'Loader',
    group_dependencies: ['packages/picasso/src/CircularProgress/'],
    components: [
      'packages/picasso/src/Loader/',
      'packages/picasso/src/CircularProgress/',
    ],
    instability: 0,
    responsibility: 5,
    accumulative_instability: 0,
    accumulative_responsibility: 33,
  },
  {
    group_name: 'Popper',
    group_dependencies: ['packages/picasso/src/utils/'],
    components: ['packages/picasso/src/Popper/'],
    instability: 1,
    responsibility: 5,
    accumulative_instability: 2,
    accumulative_responsibility: 20,
  },
  {
    group_name: 'Avatar',
    group_dependencies: [
      'packages/picasso/src/AvatarDropzoneSvg/',
      'packages/picasso/src/Logo/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/AvatarGroup/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Image/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Avatar/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/AvatarCompound/',
      'packages/picasso/src/Avatar/',
      'packages/picasso/src/AvatarGroup/',
      'packages/picasso/src/AvatarDropzoneSvg/',
      'packages/picasso/src/Image/',
    ],
    instability: 5,
    responsibility: 5,
    accumulative_instability: 30,
    accumulative_responsibility: 21,
  },
  {
    group_name: 'Logo',
    group_dependencies: ['packages/picasso/src/Icon/'],
    components: ['packages/picasso/src/Logo/'],
    instability: 1,
    responsibility: 2,
    accumulative_instability: 2,
    accumulative_responsibility: 13,
  },
  {
    group_name: 'AvatarUpload',
    group_dependencies: [
      'packages/picasso/src/AvatarDropzoneSvg/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Loader/',
      'packages/picasso/src/Avatar/',
    ],
    components: ['packages/picasso/src/AvatarUpload/'],
    instability: 5,
    responsibility: 0,
    accumulative_instability: 21,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Badge',
    group_dependencies: [],
    components: ['packages/picasso/src/Badge/'],
    instability: 0,
    responsibility: 1,
    accumulative_instability: 0,
    accumulative_responsibility: 3,
  },
  {
    group_name: 'Breadcrumbs',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Breadcrumbs/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/BreadcrumbsItem/',
    ],
    components: [
      'packages/picasso/src/Breadcrumbs/',
      'packages/picasso/src/BreadcrumbsCompound/',
      'packages/picasso/src/BreadcrumbsItem/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 12,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Checkbox',
    group_dependencies: [
      'packages/picasso/src/FormControlLabel/',
      'packages/picasso/src/CheckboxGroup/',
      'packages/picasso/src/Grid/',
      'packages/picasso/src/Checkbox/',
      'packages/picasso/src/GridItem/',
      'packages/picasso/src/GridCompound/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/FormLabel/',
    ],
    components: [
      'packages/picasso/src/CheckboxCompound/',
      'packages/picasso/src/Checkbox/',
      'packages/picasso/src/CheckboxGroup/',
    ],
    instability: 6,
    responsibility: 1,
    accumulative_instability: 31,
    accumulative_responsibility: 24,
  },
  {
    group_name: 'Switch',
    group_dependencies: ['packages/picasso/src/FormControlLabel/'],
    components: ['packages/picasso/src/Switch/'],
    instability: 1,
    responsibility: 0,
    accumulative_instability: 4,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'SkeletonLoader',
    group_dependencies: [
      'packages/picasso/src/MediaSkeletonLoader/',
      'packages/picasso/src/HeaderLoader/',
      'packages/picasso/src/ButtonLoader/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/TypographyLoader/',
      'packages/picasso/src/utils/',
    ],
    components: [
      'packages/picasso/src/SkeletonLoader/',
      'packages/picasso/src/ButtonLoader/',
      'packages/picasso/src/HeaderLoader/',
      'packages/picasso/src/MediaSkeletonLoader/',
      'packages/picasso/src/TypographyLoader/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 18,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Radio',
    group_dependencies: [
      'packages/picasso/src/Radio/',
      'packages/picasso/src/FormControlLabel/',
      'packages/picasso/src/Grid/',
      'packages/picasso/src/GridItem/',
      'packages/picasso/src/GridCompound/',
      'packages/picasso/src/RadioGroup/',
    ],
    components: [
      'packages/picasso/src/RadioCompound/',
      'packages/picasso/src/Radio/',
      'packages/picasso/src/RadioGroup/',
    ],
    instability: 4,
    responsibility: 1,
    accumulative_instability: 21,
    accumulative_responsibility: 24,
  },
  {
    group_name: 'Dropdown',
    group_dependencies: [
      'packages/picasso/src/Popover/',
      'packages/picasso/src/Popper/',
      'packages/picasso/src/DropdownArrow/',
      'packages/picasso/src/Paper/',
      'packages/picasso/src/Dropdown/',
      'packages/picasso/src/utils/',
    ],
    components: [
      'packages/picasso/src/DropdownCompound/',
      'packages/picasso/src/Dropdown/',
      'packages/picasso/src/DropdownArrow/',
      'packages/picasso/src/Popover/',
    ],
    instability: 3,
    responsibility: 4,
    accumulative_instability: 14,
    accumulative_responsibility: 41,
  },
  {
    group_name: 'Paper',
    group_dependencies: [],
    components: ['packages/picasso/src/Paper/'],
    instability: 0,
    responsibility: 2,
    accumulative_instability: 0,
    accumulative_responsibility: 13,
  },
  {
    group_name: 'Calendar',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/CalendarIndicators/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/CalendarContext/',
      'packages/picasso/src/CalendarContainer/',
      'packages/picasso/src/CalendarMonthHeader/',
      'packages/picasso/src/Calendar/',
      'packages/picasso/src/CalendarDay/',
    ],
    components: [
      'packages/picasso/src/Calendar/',
      'packages/picasso/src/CalendarContainer/',
      'packages/picasso/src/CalendarContext/',
      'packages/picasso/src/CalendarDay/',
      'packages/picasso/src/CalendarMonthHeader/',
      'packages/picasso/src/CalendarIndicators/',
    ],
    instability: 4,
    responsibility: 2,
    accumulative_instability: 38,
    accumulative_responsibility: 2,
  },
  {
    group_name: 'DatePicker',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/Popper/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Input/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Calendar/',
      'packages/picasso/src/CalendarDay/',
    ],
    components: ['packages/picasso/src/DatePicker/'],
    instability: 9,
    responsibility: 0,
    accumulative_instability: 36,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Carousel',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/CarouselGradient/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/CarouselNavigation/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Carousel/',
      'packages/picasso/src/CarouselGradient/',
      'packages/picasso/src/CarouselNavigation/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 18,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Grid',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Grid/',
      'packages/picasso/src/GridItem/',
      'packages/picasso/src/GridCompound/',
    ],
    components: [
      'packages/picasso/src/Grid/',
      'packages/picasso/src/GridCompound/',
      'packages/picasso/src/GridItem/',
      'packages/picasso/src/FieldRequirements/',
    ],
    instability: 2,
    responsibility: 6,
    accumulative_instability: 10,
    accumulative_responsibility: 12,
  },
  {
    group_name: 'Drawer',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/DrawerTitle/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Drawer/',
      'packages/picasso/src/DrawerTitle/',
    ],
    instability: 5,
    responsibility: 0,
    accumulative_instability: 21,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Dropzone',
    group_dependencies: [
      'packages/picasso/src/FormError/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/FileList/',
      'packages/picasso/src/FormHint/',
    ],
    components: ['packages/picasso/src/Dropzone/'],
    instability: 7,
    responsibility: 0,
    accumulative_instability: 27,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Form',
    group_dependencies: [
      'packages/picasso/src/FormError/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/FormHint/',
      'packages/picasso/src/Form/',
      'packages/picasso/src/FormField/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/FormLabel/',
      'packages/picasso/src/FormCompound/',
    ],
    components: [
      'packages/picasso/src/FormCompound/',
      'packages/picasso/src/Form/',
      'packages/picasso/src/FormError/',
      'packages/picasso/src/FormHint/',
      'packages/picasso/src/FormField/',
      'packages/picasso/src/FormControlLabel/',
      'packages/picasso/src/FormLabel/',
      'packages/picasso/src/FieldsLayout/',
    ],
    instability: 3,
    responsibility: 12,
    accumulative_instability: 27,
    accumulative_responsibility: 30,
  },
  {
    group_name: 'EmptyState',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/EmptyStateCollection/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/EmptyStatePage/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/EmptyState/',
      'packages/picasso/src/EmptyStateCollection/',
      'packages/picasso/src/EmptyStatePage/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 12,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'EnvironmentBanner',
    group_dependencies: [],
    components: ['packages/picasso/src/EnvironmentBanner/'],
    instability: 0,
    responsibility: 0,
    accumulative_instability: 0,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'FileInput',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Tooltip/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/FileListItem/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/ProgressBar/',
      'packages/picasso/src/TypographyOverflow/',
      'packages/picasso/src/Loader/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/FileInput/',
      'packages/picasso/src/FileList/',
      'packages/picasso/src/FormHint/',
    ],
    components: [
      'packages/picasso/src/FileInput/',
      'packages/picasso/src/FileList/',
      'packages/picasso/src/FileListItem/',
      'packages/picasso/src/ProgressBar/',
    ],
    instability: 10,
    responsibility: 1,
    accumulative_instability: 76,
    accumulative_responsibility: 1,
  },
  {
    group_name: 'Tooltip',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/Tooltip/'],
    instability: 2,
    responsibility: 4,
    accumulative_instability: 4,
    accumulative_responsibility: 10,
  },
  {
    group_name: 'Slider',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/Tooltip/',
      'packages/picasso/src/SliderValueLabel/',
    ],
    components: [
      'packages/picasso/src/Slider/',
      'packages/picasso/src/SliderValueLabel/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 7,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'TypographyOverflow',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/Tooltip/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/TypographyOverflow/'],
    instability: 3,
    responsibility: 3,
    accumulative_instability: 7,
    accumulative_responsibility: 4,
  },
  {
    group_name: 'FormAutoSaveIndicator',
    group_dependencies: [
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/FormAutoSaveIndicator/'],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 4,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Helpbox',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/HelpboxActions/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Helpbox/',
      'packages/picasso/src/HelpboxTitle/',
      'packages/picasso/src/HelpboxContent/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Helpbox/',
      'packages/picasso/src/HelpboxCompound/',
      'packages/picasso/src/HelpboxActions/',
      'packages/picasso/src/HelpboxContent/',
      'packages/picasso/src/HelpboxTitle/',
    ],
    instability: 4,
    responsibility: 0,
    accumulative_instability: 30,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'OutlinedInput',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/InputValidIconAdornment/',
    ],
    components: ['packages/picasso/src/OutlinedInput/'],
    instability: 5,
    responsibility: 9,
    accumulative_instability: 18,
    accumulative_responsibility: 23,
  },
  {
    group_name: 'Input',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/InputIconAdornment/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/InputLabel/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/InputValidIconAdornment/',
      'packages/picasso/src/InputLimitAdornment/',
      'packages/picasso/src/InputBase/',
    ],
    components: [
      'packages/picasso/src/InputBase/',
      'packages/picasso/src/Input/',
      'packages/picasso/src/InputLabel/',
    ],
    instability: 8,
    responsibility: 10,
    accumulative_instability: 41,
    accumulative_responsibility: 18,
  },
  {
    group_name: 'InputAdornment',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/InputIconAdornment/',
      'packages/picasso/src/InputValidIconAdornment/',
      'packages/picasso/src/InputLimitAdornment/',
      'packages/picasso/src/InputMultilineAdornment/',
    ],
    instability: 2,
    responsibility: 10,
    accumulative_instability: 6,
    accumulative_responsibility: 62,
  },
  {
    group_name: 'PasswordInput',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/InputBase/',
    ],
    components: ['packages/picasso/src/PasswordInput/'],
    instability: 5,
    responsibility: 0,
    accumulative_instability: 28,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'List',
    group_dependencies: [
      'packages/picasso/src/ListItem/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/List/',
    ],
    components: [
      'packages/picasso/src/List/',
      'packages/picasso/src/ListItem/',
    ],
    instability: 4,
    responsibility: 0,
    accumulative_instability: 16,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Menu',
    group_dependencies: [
      'packages/picasso/src/Popper/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Menu/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Link/',
      'packages/picasso/src/MenuItem/',
      'packages/picasso/src/Paper/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Avatar/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/MenuCompound/',
      'packages/picasso/src/Menu/',
      'packages/picasso/src/MenuItem/',
    ],
    instability: 8,
    responsibility: 7,
    accumulative_instability: 34,
    accumulative_responsibility: 23,
  },
  {
    group_name: 'Modal',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Modal/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/ModalActions/',
      'packages/picasso/src/ModalContent/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/ModalTitle/',
    ],
    components: [
      'packages/picasso/src/Modal/',
      'packages/picasso/src/ModalCompound/',
      'packages/picasso/src/ModalActions/',
      'packages/picasso/src/ModalContent/',
      'packages/picasso/src/ModalTitle/',
    ],
    instability: 4,
    responsibility: 2,
    accumulative_instability: 30,
    accumulative_responsibility: 2,
  },
  {
    group_name: 'PromptModal',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Modal/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/ModalCompound/',
      'packages/picasso/src/Container/',
    ],
    components: ['packages/picasso/src/PromptModal/'],
    instability: 6,
    responsibility: 0,
    accumulative_instability: 24,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'DateSelect',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/Select/',
    ],
    components: [
      'packages/picasso/src/MonthSelect/',
      'packages/picasso/src/YearSelect/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 17,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Select',
    group_dependencies: [
      'packages/picasso/src/NativeSelectOptions/',
      'packages/picasso/src/NonNativeSelectLimitFooter/',
      'packages/picasso/src/NativeSelect/',
      'packages/picasso/src/InputLabel/',
      'packages/picasso/src/Menu/',
      'packages/picasso/src/SelectCaret/',
      'packages/picasso/src/NonNativeSelect/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/NonNativeSelectOption/',
      'packages/picasso/src/ScrollMenu/',
      'packages/picasso/src/NonNativeSelectOptions/',
      'packages/picasso/src/InputBase/',
      'packages/picasso/src/NonNativeSelectLoader/',
      'packages/picasso/src/Popper/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Input/',
      'packages/picasso/src/SelectOptions/',
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/NativeSelectPlaceholder/',
      'packages/picasso/src/SelectBase/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/MenuItem/',
      'packages/picasso/src/Loader/',
      'packages/picasso/src/utils/',
    ],
    components: [
      'packages/picasso/src/Select/',
      'packages/picasso/src/SelectBase/',
      'packages/picasso/src/SelectCaret/',
      'packages/picasso/src/SelectOptions/',
      'packages/picasso/src/ScrollMenu/',
      'packages/picasso/src/NativeSelect/',
      'packages/picasso/src/NativeSelectPlaceholder/',
      'packages/picasso/src/NativeSelectOptions/',
      'packages/picasso/src/NonNativeSelect/',
      'packages/picasso/src/NonNativeSelectOptions/',
      'packages/picasso/src/NonNativeSelectOption/',
      'packages/picasso/src/NonNativeSelectLimitFooter/',
      'packages/picasso/src/NonNativeSelectLoader/',
    ],
    instability: 14,
    responsibility: 2,
    accumulative_instability: 237,
    accumulative_responsibility: 4,
  },
  {
    group_name: 'Note',
    group_dependencies: [
      'packages/picasso/src/NoteTitle/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/NoteSubtitle/',
      'packages/picasso/src/Note/',
      'packages/picasso/src/NoteContent/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Note/',
      'packages/picasso/src/NoteCompound/',
      'packages/picasso/src/NoteContent/',
      'packages/picasso/src/NoteSubtitle/',
      'packages/picasso/src/NoteTitle/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 12,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Notification',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Notification/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/NotificationActions/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Notification/',
      'packages/picasso/src/NotificationActions/',
      'packages/picasso/src/NotificationCompound/',
    ],
    instability: 4,
    responsibility: 3,
    accumulative_instability: 22,
    accumulative_responsibility: 47,
  },
  {
    group_name: 'NumberInput',
    group_dependencies: [
      'packages/picasso/src/InputAdornment/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/NumberInputEndAdornment/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/InputBase/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/NumberInput/',
      'packages/picasso/src/NumberInputEndAdornment/',
    ],
    instability: 7,
    responsibility: 0,
    accumulative_instability: 35,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'OverviewBlock',
    group_dependencies: [
      'packages/picasso/src/OverviewBlock/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/OverviewBlockRow/',
      'packages/picasso/src/OverviewBlockGroup/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/OverviewBlock/',
      'packages/picasso/src/OverviewBlockCompound/',
      'packages/picasso/src/OverviewBlockGroup/',
      'packages/picasso/src/OverviewBlockRow/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 15,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Page',
    group_dependencies: [
      'packages/picasso/src/PageArticle/',
      'packages/picasso/src/Notification/',
      'packages/picasso/src/PageContent/',
      'packages/picasso/src/PageTopBarCompound/',
      'packages/picasso/src/PageFooter/',
      'packages/picasso/src/NotificationActions/',
      'packages/picasso/src/PageSidebar/',
      'packages/picasso/src/Autocomplete/',
      'packages/picasso/src/PageHelmet/',
      'packages/picasso/src/PageTopBarMenu/',
      'packages/picasso/src/PageBanner/',
      'packages/picasso/src/PageTopBar/',
      'packages/picasso/src/Page/',
      'packages/picasso/src/PageAutocomplete/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/PageHamburger/',
    ],
    components: [
      'packages/picasso/src/Page/',
      'packages/picasso/src/PageArticle/',
      'packages/picasso/src/PageAutocomplete/',
      'packages/picasso/src/PageCompound/',
      'packages/picasso/src/PageContent/',
      'packages/picasso/src/PageFooter/',
      'packages/picasso/src/PageHelmet/',
      'packages/picasso/src/PageBanner/',
    ],
    instability: 9,
    responsibility: 1,
    accumulative_instability: 159,
    accumulative_responsibility: 7,
  },
  {
    group_name: 'PageTopBar',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/TopBarItem/',
      'packages/picasso/src/TopBarMenu/',
      'packages/picasso/src/DropdownCompound/',
      'packages/picasso/src/Logo/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/UserBadge/',
      'packages/picasso/src/Menu/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/SidebarItem/',
      'packages/picasso/src/Dropdown/',
      'packages/picasso/src/PageTopBar/',
      'packages/picasso/src/Page/',
      'packages/picasso/src/Avatar/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/PageHamburger/',
    ],
    components: [
      'packages/picasso/src/PageTopBar/',
      'packages/picasso/src/PageTopBarCompound/',
      'packages/picasso/src/PageTopBarMenu/',
      'packages/picasso/src/TopBarItem/',
      'packages/picasso/src/TopBarMenu/',
      'packages/picasso/src/PageHamburger/',
    ],
    instability: 13,
    responsibility: 6,
    accumulative_instability: 123,
    accumulative_responsibility: 14,
  },
  {
    group_name: 'PageSidebar',
    group_dependencies: [
      'packages/picasso/src/Tooltip/',
      'packages/picasso/src/Menu/',
      'packages/picasso/src/PageSidebar/',
      'packages/picasso/src/Badge/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/PageHamburger/',
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/SidebarItemContent/',
      'packages/picasso/src/Indicator/',
      'packages/picasso/src/Accordion/',
      'packages/picasso/src/Dropdown/',
      'packages/picasso/src/SidebarMenu/',
      'packages/picasso/src/TagRectangular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/MenuItem/',
      'packages/picasso/src/SidebarItem/',
      'packages/picasso/src/PageTopBar/',
      'packages/picasso/src/SidebarLogo/',
      'packages/picasso/src/utils/',
    ],
    components: [
      'packages/picasso/src/PageSidebar/',
      'packages/picasso/src/SidebarLogo/',
      'packages/picasso/src/SidebarItem/',
      'packages/picasso/src/SidebarMenu/',
      'packages/picasso/src/SidebarItemContent/',
    ],
    instability: 15,
    responsibility: 2,
    accumulative_instability: 156,
    accumulative_responsibility: 9,
  },
  {
    group_name: 'PageHead',
    group_dependencies: [
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
    ],
    components: ['packages/picasso/src/PageHead/'],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 4,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Pagination',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/PaginationButton/',
    ],
    components: [
      'packages/picasso/src/Pagination/',
      'packages/picasso/src/PaginationButton/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 15,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Quote',
    group_dependencies: [
      'packages/picasso/src/QuoteMark/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
    ],
    components: [
      'packages/picasso/src/Quote/',
      'packages/picasso/src/QuoteMark/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 6,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Rating',
    group_dependencies: [
      'packages/picasso/src/RatingStars/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/RatingIcon/',
      'packages/picasso/src/RatingThumbs/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/Rating/',
      'packages/picasso/src/RatingStars/',
      'packages/picasso/src/RatingThumbs/',
      'packages/picasso/src/RatingIcon/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 10,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Section',
    group_dependencies: [
      'packages/picasso/src/ButtonCircular/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
    ],
    components: ['packages/picasso/src/Section/'],
    instability: 5,
    responsibility: 0,
    accumulative_instability: 16,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'TreeView',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Button/',
      'packages/picasso/src/TreeView/',
    ],
    components: [
      'packages/picasso/src/StaticTreeView/',
      'packages/picasso/src/TreeView/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 15,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Step',
    group_dependencies: [
      'packages/picasso/src/StepIcon/',
      'packages/picasso/src/Stepper/',
      'packages/picasso/src/StepConnector/',
      'packages/picasso/src/Step/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/TypographyOverflow/',
      'packages/picasso/src/StepperVertical/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/StepLabel/',
    ],
    components: [
      'packages/picasso/src/Step/',
      'packages/picasso/src/StepConnector/',
      'packages/picasso/src/StepIcon/',
      'packages/picasso/src/StepLabel/',
      'packages/picasso/src/Stepper/',
      'packages/picasso/src/StepperCompound/',
      'packages/picasso/src/StepperVertical/',
    ],
    instability: 3,
    responsibility: 0,
    accumulative_instability: 26,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Tabs',
    group_dependencies: [
      'packages/picasso/src/TabScrollButton/',
      'packages/picasso/src/Tabs/',
      'packages/picasso/src/UserBadge/',
      'packages/picasso/src/Tab/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/TabDescription/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/TypographyOverflow/',
      'packages/picasso/src/TabLabel/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/Container/',
    ],
    components: [
      'packages/picasso/src/TabScrollButton/',
      'packages/picasso/src/Tabs/',
      'packages/picasso/src/Tab/',
      'packages/picasso/src/TabDescription/',
      'packages/picasso/src/TabsCompound/',
      'packages/picasso/src/TabLabel/',
    ],
    instability: 6,
    responsibility: 0,
    accumulative_instability: 46,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Table',
    group_dependencies: [
      'packages/picasso/src/Typography/',
      'packages/picasso/src/TableSectionHead/',
      'packages/picasso/src/TableExpandableRow/',
      'packages/picasso/src/TableCell/',
      'packages/picasso/src/Table/',
      'packages/picasso/src/TableHead/',
      'packages/picasso/src/TableBody/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/TableRow/',
      'packages/picasso/src/TableFooter/',
    ],
    components: [
      'packages/picasso/src/Table/',
      'packages/picasso/src/TableBody/',
      'packages/picasso/src/TableCell/',
      'packages/picasso/src/TableCompound/',
      'packages/picasso/src/TableExpandableRow/',
      'packages/picasso/src/TableFooter/',
      'packages/picasso/src/TableHead/',
      'packages/picasso/src/TableRow/',
      'packages/picasso/src/TableSectionHead/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 20,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Tag',
    group_dependencies: [
      'packages/picasso/src/TagConnection/',
      'packages/picasso/src/Typography/',
      'packages/picasso/src/TagGroup/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Chip/',
      'packages/picasso/src/Indicator/',
      'packages/picasso/src/Tag/',
      'packages/picasso/src/utils/',
      'packages/picasso/src/TagCheckable/',
      'packages/picasso/src/TagRectangular/',
    ],
    components: [
      'packages/picasso/src/Tag/',
      'packages/picasso/src/TagCheckable/',
      'packages/picasso/src/TagCompound/',
      'packages/picasso/src/TagConnection/',
      'packages/picasso/src/TagGroup/',
      'packages/picasso/src/TagRectangular/',
      'packages/picasso/src/Chip/',
      'packages/picasso/src/Indicator/',
    ],
    instability: 3,
    responsibility: 3,
    accumulative_instability: 27,
    accumulative_responsibility: 7,
  },
  {
    group_name: 'Tagselector',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/FieldsLayout/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/TagSelector/',
      'packages/picasso/src/Input/',
      'packages/picasso/src/Autocomplete/',
      'packages/picasso/src/TagSelectorLabel/',
      'packages/picasso/src/Tag/',
      'packages/picasso/src/TagSelectorInput/',
      'packages/picasso/src/InputBase/',
    ],
    components: [
      'packages/picasso/src/TagSelector/',
      'packages/picasso/src/TagSelectorLabel/',
      'packages/picasso/src/TagSelectorCompound/',
      'packages/picasso/src/TagSelectorInput/',
    ],
    instability: 7,
    responsibility: 0,
    accumulative_instability: 67,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Timepicker',
    group_dependencies: [
      'packages/picasso/src/utils/',
      'packages/picasso/src/OutlinedInput/',
      'packages/picasso/src/Icon/',
      'packages/picasso/src/Input/',
    ],
    components: ['packages/picasso/src/TimePicker/'],
    instability: 4,
    responsibility: 0,
    accumulative_instability: 19,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Timeline',
    group_dependencies: [
      'packages/picasso/src/TimelineRow/',
      'packages/picasso/src/Container/',
      'packages/picasso/src/Typography/',
    ],
    components: [
      'packages/picasso/src/Timeline/',
      'packages/picasso/src/TimelineRow/',
    ],
    instability: 2,
    responsibility: 0,
    accumulative_instability: 6,
    accumulative_responsibility: 0,
  },
  {
    group_name: 'Test-Utils',
    group_dependencies: [],
    components: ['packages/picasso/src/test-utils/'],
    instability: 0,
    responsibility: 0,
    accumulative_instability: 0,
    accumulative_responsibility: 0,
  },
]
