@Library('globalLibrary@master') _
pipeline {

  agent { label 'docker' }

  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
  }

  triggers {
    cron('0 3 * * *')
  }

  environment {
    GITHUB_TOKEN = credentials('TOPTAL_DEVBOT_TOKEN')
  }

  stages {
    stage('Kill outdated docs') {
        steps {
            script {
              sshagent(credentials: ['SSH_PROVBOT_STAGING']) { //provbot (jenkins/provbot)
                existingReleases = sh(returnStdout: true, script: 'ssh docs@docs.staging.toptal.net "find ~/docs/picasso/ -maxdepth 1 -mindepth 1 -type d | xargs basename -a"').split("\n")
                openReleases = sh(returnStdout: true, script: "curl https://api.github.com/repos/toptal/picasso/pulls | jq -r '.[] | .head.ref'")
                releasesToDelete = existingReleases.findAll { it != "master" && !openReleases.contains(it) }
                foldersToDelete = releasesToDelete.collect { "'${it}'" }

                foldersToDelete.each {
                  info "Folder [${it}] marked for removal"
                }

                if (!foldersToDelete.isEmpty()) {
                  foldersToDelete = foldersToDelete.join(' ')
                  sh """
                    ssh docs@docs.staging.toptal.net "cd ~/docs/picasso && rm -rf ${foldersToDelete}"
                  """
                } else {
                  success "Nothing to remove"
                }
              }//sshagent
            }//script
        }//steps
    }//stage
  }//stages
  post {
    always {
      script {
        sendBuildData(currentBuild)
      }
    }
  }
}//pipeline
