import figma from 'figma'

// Per-icon data comes from Icon.figma.batch.json, generated by
// bin/generate-icon-code-connect.mjs
const {
  id,
  name,
  sizes,
  sizeProperty = 'Size',
} = figma.batch as {
  id: string
  name: string
  sizes: string[]
  sizeProperty?: string
}

const figmaSize =
  figma.selectedInstance.getEnum(sizeProperty, {
    '16': '16',
    '24': '24',
    '32': '32',
  }) ?? sizes[0]
// Picasso ships 16 and 24 for every icon but 32 only for a few, so a missing
// size falls back to the largest one Picasso has
const size = sizes.includes(figmaSize) ? figmaSize : sizes[sizes.length - 1]
const component = `${name}${size}`

export default {
  id,
  imports: [`import { ${component} } from '@toptal/picasso'`],
  example: figma.code`${
    size === figmaSize ? '' : `/* Picasso has no ${name}${figmaSize} */\n`
  }<${component} />`,
  metadata: { nestable: true },
} satisfies CodeConnectTemplate
