@Library('globalLibrary@master') _

helper = new helpers.Helpers()
ghHelper = new helpers.GithubNotifyHelper()

downStreamBuilds = []
def VERSION

pipeline {
  agent {
    docker {
      image 'gcr.io/compute-engine-1069/platform_tests'
    }
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 15, unit: 'MINUTES')
    skipDefaultCheckout()
  }

  environment {
    GREN_GITHUB_TOKEN = credentials('toptal-devbot-personal-token')
    GITHUB_TOKEN = credentials('toptal-devbot-token-github-notify')
    NPM_TOKEN = credentials('npm-token-for-toptal-private-registry-publish')
  }

  stages {
    stage('Git checkout PR') {
      steps {
        info "== Checking out master"
          gitCheckout(
            branches: "master",
            credentials: [username: 'git', description: 'jenkins/picasso'],
            url: 'git@github.com:toptal/picasso.git',
            refspec: '+refs/heads/master:refs/remotes/origin/master',
            additionalBehaviours: [
              cleanBeforeCheckout         : true,
              advancedCheckoutBehaviour: [timeout: 30],
              advancedCloneBehaviour   : [depth: 0, noTags: false, reference: '', shallow: false, timeout: 30]
            ]
          )

        info "Git commit: ${gitCommit()}"
        info "Git branch: ${gitBranch()}"
        success "Checkout finished"
      }
    }//stage

    stage('Build new Docker image') {
      steps {
        info "== Building new docker image"
        script {
          downStreamBuilds[0] = buildWithParameters(
            jobName: 'picasso-build-image',
            propagate: false,
            wait: true,
            parameters: [
              BRANCH: 'master'
            ]
          )
        }
      }
    }

    stage('Run release') {
      steps {

        sshagent (credentials: ['picasso-ssh-deploy-key']) {
            sh "git config user.email 'bot@toptal.com'"
            sh "git config user.name 'toptal-bot'"
            sh "mkdir -p ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts"
            sh "git tag -l"
            sh "git tag -d \$(git tag)"
            sh "git tag -l"
            sh "yarn"
            sh "./bin/release"
            sh "yarn build"
            sh "npm publish"
        }
        script {
            VERSION = sh(returnStdout: true, script: 'cat package.json | jq ".version" -r').trim()
        }
      } //steps
    }//stage

    stage('Deploy documentation') {
      steps {
        info "== Deploying docs"
        script {
          downStreamBuilds[1] = buildWithParameters(
            jobName: "picasso-docs",
            propagate: false,
            wait: true,
            parameters: [
              CI_NODE_INDEX: "0"
            ]
          )
        }
      }
    }

    stage('Build results') {
      steps {
        script {
          helper.printBuildsResults(downStreamBuilds)
          helper.setBuildStatus(downStreamBuilds)
        }
      }
    }
  }//stages
  post {
      success {
          script {
            // https://api.slack.com/docs/message-attachments
            data =
            '''[
              {
                "title": ":frontend-experience: New version {VERSION} of picasso was released",
                "fallback": "New version {VERSION} of picasso was released",
                "color": "#36a64f",
                "fields": [
                  {
                    "title": "Documentation",
                    "value": "<https://picasso.toptal.net|See live documentation>",
                    "short": "true"
                  },
                  {
                    "title": "Release",
                    "value": "<https://github.com/toptal/picasso/releases/tag/v{VERSION}|See release v{VERSION}>",
                    "short": "true"
                  }
                ]
              }
            ]'''
            attachments = data.replace('{VERSION}', VERSION)
            slackSend color: 'good', channel: '-frontend-exp-core', attachments: attachments
          }
      }
  }
}//pipeline
