export default {
  BOTTOM_DOMAIN: 0,
  HIGHLIGHT_BOTTOM_START_POINT: 0,
  HIGHLIGHT_BOTTOM_FILL_OPACITY: 0.1,
  HIGHLIGHT_TOP_FILL_OPACITY: 0.1,
  HIGHLIGHT_TOP_HEIGHT: 0.1,
  TOP_DOMAIN_OFFSET: 1,
  TICK_MARGIN: 16,
  MIN_TICK_GAP: -10,
  DEFAULT_MARGIN: 20,
  TICK_LINE: false,
  AXIS_LINE: false,
  IS_ANIMATION_ACTIVE: false
}
