name: Alpha Package release
description: Builds project and pushes a new alpha release to NPM (copy paster from davinci-github-actions repo)
outputs:
  versions:
    description: 'List of new versions as output of `.version` file || string'
    value: ${{ steps.publish-package.outputs.versions }}

inputs:
  branch:
    required: true
    description: 'Name of the branch that will be published || string'
  root-folder:
    required: false
    description: 'Root folder of a package to be published || string'
  node-version:
    required: false
    default: 20
    description: 'Node.js version used. The action is guaranteed to work only with Node.js@20 (default value)'

runs:
  using: composite
  steps:
    - name: Log
      shell: bash
      run: |
        echo "Starting to publish package"

    - name: Set up node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Set up npm
      shell: bash
      run: yarn global add npm@11.5.1

    - name: Install dependencies and build package
      shell: bash
      run: |
        yarn install
        yarn build:package

    # TODO: remove "--nonMonorepo" before merge
    - name: Publish package
      id: publish-package
      shell: bash
      env:
        BRANCH: ${{ inputs.branch }}
        ROOT_FOLDER: ${{ inputs.root-folder }}
      run: |
        # set .github folder as an unchanged, because lerna throws an error if there are uncommitted changes
        git checkout .github/

        yarn davinci-engine publish-package \
          --alpha \
          --outputVersion .version \
          --branch "$BRANCH" ${ROOT_FOLDER:+"--publishRootFolder=$ROOT_FOLDER"} \
          @toptal/base-tailwind

        versions=$(cat .version)
        [ -z "$versions" ] && exit 1

        echo "versions=$versions" >> $GITHUB_OUTPUT
