@Library('globalLibrary@master') _

ghHelper = new helpers.GithubNotifyHelper()
helper = new helpers.Helpers()
repoName = 'picasso'

pipeline {
  agent { label 'docker' }

  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 45, unit: 'MINUTES')
    skipDefaultCheckout()
  }

  parameters {
    string(name: 'BRANCH', defaultValue: 'master', description: 'Branch or tag to build')
    string(name: 'COMMIT_ID', defaultValue: '', description: 'Commit hash from which docs should be created')
  }

  environment {
    DANGER_GITHUB_API_TOKEN = credentials('toptal-devbot-personal-token')
  }

  stages {
    // Perform this only for PRs
    stage('Git checkout PR') {
      steps {
        info "== Checking out Git revision ${COMMIT_ID}"
        gitCheckout(
          branches: "${COMMIT_ID}",
          credentials: [username: 'toptal-build', description: 'toptal-build-ssh-key'],
          url: 'git@github.com:toptal/picasso.git',
          refspec: "+refs/heads/${BRANCH}:refs/remotes/origin/${BRANCH} +refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*",
          additionalBehaviours: [
                  advancedCheckoutBehaviour: [timeout: 120],
                  advancedCloneBehaviour   : [depth: 0, noTags: true, reference: '', shallow: false, timeout: 340],
                  cleanBeforeCheckout      : false,
                  calculateChangelog       : [compareRemote: 'origin', compareTarget: "${BRANCH}"]
          ]
        )

        info "Git commit: ${COMMIT_ID}"
        info "Git branch: ${BRANCH}"
        success 'Checkout finished'
      }
    }//stage

    stage('Run visual tests') {
      when {
        expression {
          ghprbMatchesComment(/test:visual|visual|all/)
        }
      }

      steps {
        info 'Run visual tests...'
        script {
          ghHelper.notifyPR('Visual Tests', 'PENDING', 'running', "${COMMIT_ID}", "${BUILD_URL}", repoName)

          def DIR = pwd() // can't be replaced with ${PWD}, because it's pointing to the jenkins_root folder
          sh """
            mkdir -p ${DIR}/__diff_output__

            docker run --rm \
            -v ${DIR}/__diff_output__:/app/__diff_output__ \
            gcr.io/toptal-hub/${repoName}:${COMMIT_ID} \
            yarn run test:visual:ci
          """
        }
      } //steps

      post {
        success {
          success "Visual Tests"
          script {
            ghHelper.notifyPR('Visual Tests', 'SUCCESS', 'Success', "${COMMIT_ID}", "${BUILD_URL}/Visual_20Regression_20Tests/", repoName)
          }
        }
        failure {
          err "Visual Tests"
          script {
            ghHelper.notifyPR('Visual Tests', 'ERROR', 'Job failed', "${COMMIT_ID}","${BUILD_URL}/Visual_20Regression_20Tests/", repoName)
          }
        }
      } //post
    }//stage
  }//stages

  post {
    always {
      script {
        archiveArtifacts(
          artifacts: "__diff_output__/latest/**/*.*",
          fingerprint: true,
          allowEmptyArchive: true
        )

        publishHTML([
          allowMissing: true,
          alwaysLinkToLastBuild: true,
          keepAll: true,
          reportDir: '__diff_output__/latest',
          reportFiles: 'index.html',
          reportName: 'Visual Regression Tests',
          reportTitles: 'All files'
        ])

        sendBuildData(currentBuild)
      }
    }
  }
}//pipeline
