name: Format dependabot PR title to Totpal's commit format
on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  format_title:
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ['org/toptal', 'os/linux', 'arch/x64', 'size/large']
    steps:
      - uses: toptal/davinci-github-actions/pr-conventional-to-toptal-commits@fx-4409-adoption-of-toptal-commit-message-format
