name: Format dependabot PR title to Toptal's commit format
on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  format_title:
    name: Format title
    permissions: write-all
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - uses: toptal/davinci-github-actions/pr-conventional-to-toptal-commits@v12.7.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
