name: Format dependabot PR title to Toptal's commit format
on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  format_title:
    name: Format title
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - name: GSM Secrets
        id: secrets_manager
        uses: toptal/davinci-github-actions/gsm-secrets@master
        with:
          workload_identity_provider: ${{ secrets.IDENTITY_POOL }}
          service_account: ${{ secrets.SA_IDENTITY_POOL }}
          secrets_name: |-
            TOPTAL_DEVBOT_TOKEN:toptal-ci/TOPTAL_DEVBOT_TOKEN

      - name: Parse secrets
        id: parse_secrets
        uses: toptal/davinci-github-actions/expose-json-outputs@master
        with:
          json: ${{ steps.secrets_manager.outputs.secrets }}

      - name: Set ENV Variables
        run: |-
          echo "GITHUB_TOKEN=${{ steps.parse_secrets.outputs.TOPTAL_DEVBOT_TOKEN }}" >> $GITHUB_ENV

      - uses: toptal/davinci-github-actions/pr-conventional-to-toptal-commits@v12.2.0
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
