name: Format dependabot PR title to Toptal commit format
on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  format_title:
    name: Format title
    permissions:
      contents: read
      pull-requests: write
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/pr-conventional-to-toptal-commits
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
