name: Format dependabot PR title to Totpal's commit format
on:
  pull_request:
    types: [opened]
    branches: [master]

jobs:
  format_title:
    name: Format title
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - uses: toptal/davinci-github-actions/pr-conventional-to-toptal-commits@v12.1.0
