name: Format dependabot PR title to Toptal's commit format
on:
  pull_request:
    types:
      - synchronize # PR was updated
      - opened # PR was open
      - reopened # PR was closed and is now open again
      - ready_for_review # PR was converted from draft to open
    branches: [master]

jobs:
  format_title:
    name: Format title
    permissions: write-all
    if: startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - uses: toptal/davinci-github-actions/pr-conventional-to-toptal-commits@v12.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
