name: Handle Labels

on:
  push:
    branches: "**"

jobs:
  handle-labels:
    if: ${{ github.event.pull_request.head.ref != 'changeset-release/master' }}
    runs-on: ubuntu-latest
    name: Call notify jira about contribution
    steps:
      - uses: actions/checkout@v2
        with:
          repository: toptal/davinci-github-actions
          token: ${{ secrets.TOPTAL_DEVBOT_TOKEN }}
          path: ./.github/actions/
          ref: "playground-branch-1"

      - uses: ./.github/actions/notify-jira-about-contribution
        with:
          team: frontend-experience-eng
          repo: ${{ github.event.repository.name }}
          pull-number: ${{ github.event.pull_request.number}}
          jira-hook: ${{ secrets.JIRA_AUTOMATION_HOOK_FOR_NEW_CONTRIBUTION }}
          github-token: ${{ secrets.TOPTAL_DEVBOT_TOKEN }}
