name: Trigger Storybook Happo tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master # triggers the flow for every PR to master
      - 'feature/**' # triggers the flow for a PR to a branch like feature/v9

    types:
      - synchronize # PR was updated
      - opened # PR was open
      - reopened # PR was closed and is now open again
      - ready_for_review # PR was converted from draft to open

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-happo:
    if: ${{ github.event.pull_request.head.ref != 'changeset-release/master' }}
    name: Trigger Storybook Happo
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout davinci GHAs
        uses: actions/checkout@v2
        with:
          repository: toptal/davinci-github-actions
          ref: v2
          token: ${{ env.TOPTAL_DEVBOT_TOKEN }}
          path: ./.github/actions/

      - uses: ./.github/actions/yarn-install

      - name: Visual Tests
        run: yarn happo:ci
        env:
          HAPPO_PROJECT: Picasso/Storybook
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
