# This workflow is solely for testing the alpha package release in FF-49-enhance-publishing branch
# Normally it is called from davinci-alpha-package.yml workflow.
# TODO: delete this workflow before merge

on:
  push:
    branches:
      - FF-49-enhance-publishing

permissions:
  contents: write
  id-token: write

jobs:
  publish-alpha-package:
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: write
      id-token: write
    with:
      branch: FF-49-enhance-publishing
      alpha: true
