name: Publish Packages to NPM
description: |
  Routes package publishing to the appropriate workflow. Trusted publishing is
  tied to a single workflow, this is why the central publishing workflow is needed.

# TODO: add workflow_dispatch with alpha parameter for starting from UI
# TODO: restore alpha parameter
on:
  push:
    branches:
      - FF-49-enhance-publishing

permissions:
  contents: write
  id-token: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  publish-release-packages:
    name: Publish release packages to NPM
    if: false
    #if: ${{ !inputs.alpha }}
    runs-on: ubuntu-latest
    steps:
      - name: Empty step
        run: echo "Release packages are not supported yet"

  publish-alpha-packages:
    name: Publish alpha packages to NPM
    if: true
    # if: ${{ inputs.alpha }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger alpha packages publishing
        id: alpha-package
        uses: ./.github/actions/build-publish-alpha-package
        with:
          branch: FF-49-enhance-publishing
          root-folder: '.'
