name: Publish Packages to NPM
description: |
  Routes package publishing to the appropriate workflow. Trusted publishing is
  tied to a single workflow, this is why the central publishing workflow is needed.

# TODO: replace all "@N" with shas, we do not trust tags
# TODO: add workflow_dispatch with alpha parameter for starting from UI and comment from user
# TODO: add issue_comment for starting from pull requests
# TODO: restore alpha parameter
on:
  workflow_dispatch:
    inputs:
      alpha:
        description: Whether to publish alpha packages
        required: false
        default: true
        type: boolean
      branch:
        description: Branch to publish
        required: false
        default: master
        type: string
  # TODO: delete trigger before merge
  push:
    branches:
      - FF-49-enhance-publishing

permissions:
  contents: write
  id-token: write
  actions: write
  issues: write
  pull-requests: write

jobs:
  publish-release-packages:
    name: Publish release packages to NPM
    if: false
    # TODO: use input alpha before merge
    #if: ${{ !inputs.alpha }}
    runs-on: ubuntu-latest
    steps:
      - name: Empty step
        run: echo "Release packages are not supported yet"

  publish-alpha-packages:
    name: Publish alpha packages to NPM
    if: true
    # TODO: use input alpha before merge
    #if: ${{ inputs.alpha }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trigger alpha packages publishing
        id: alpha-package
        uses: ./.github/actions/build-publish-alpha-package
        with:
          # TODO: use input branch before merge
          #branch: ${{ inputs.branch }}
          branch: FF-49-enhance-publishing
          root-folder: '.'
