name: 'Report GHA stats to Anvil'
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Visual Testing", "Request review on PRs", "Consulting the Oracle", "Automatic Rebase"]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: toptal/actions
          token: ${{ secrets.TOPTAL_DEVBOT_TOKEN }}
          path: ./.github/common-actions/
      # Usage of this action
      - uses: ./.github/common-actions/report-to-anvil-action
        with:
          anvil_basic_auth: ${{ secrets.ANVIL_BASIC_AUTH }}
