on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - master # triggers the flow for every PR to master
      - 'feature/**' # triggers the flow for a PR to a branch like feature/v9

    types:
      - synchronize # PR was updated
      - opened # PR was open
      - reopened # PR was closed and is now open again
      - ready_for_review # PR was converted from draft to open

jobs:
  create-jira-deployment:
    runs-on: ubuntu-latest
    name: Create JIRA deployment
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      JIRA_BASE_URL: ${{ secrets.CLOUD_INSTANCE_BASE_URL }}
      JIRA_USER: ${{ secrets.TOPTAL_TRIGGERBOT_USERNAME }}
      JENKINS_BUILD_TOKEN: ${{ secrets.TOPTAL_TRIGGERBOT_BUILD_TOKEN }}
      PROXY: http://${{ secrets.HTTP_PROXY }}
      DEVBOT_TOKEN: ${{ secrets.TOPTAL_DEVBOT_TOKEN }}
      OWNER: toptal
      REPO: picasso
      ENV_NAME: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install Dependencies
      #   uses: toptal/davinci-github-actions/yarn-install@v8.0.0

      # - id: branch
      #   uses: xt0rted/pull-request-comment-branch@v2.0.0

      # - name: Check ENV Variables
      #   run: |
      #     echo "BASE_REF=${{ steps.branch.outputs.base_ref }}" >> $GITHUB_ENV
      #     echo "HEAD_REF=${{ steps.branch.outputs.head_ref }}" >> $GITHUB_ENV

      - name: Create Deployment
        uses: toptal/davinci-github-actions/create-jira-deployment@fx-4058-update-jira-deployment
        with:
          token: ${{ env.DEVBOT_TOKEN }}
          environment: ${{ env.ENV_NAME }}
          environment-url: https://www.npmjs.com/package/@toptal/picasso?activeTab=versions